### ISSUE TITLE
Create a # of tweets counter

### ISSUE THREAD

**Issue by OwainWilliams** [H5YR/High5YouRock#11]
Originally we had chatted about a way to have a number of tweets shown from a given date e.g. 

200 High Fives have been given since 01-01-2022

We can't go back in time, I don't think, with the twitter API so we would need to start counting from the date implemented on the site. 
Maybe just increment a counter in a database table?

**Comment by TECKSPEED** [comment]
Could you keep a tweet count table that would keep a count weekly or monthly? Then simply sum the number based on whatever date a user chooses?

Or perhaps a Label(string) in Umbraco that increments every time you need it too via a custom service or api controller?

**Comment by KarlButler1** [comment]
@OwainWilliams I'm going to pick this up and look into this.

Planning on building out a custom db table to capture the total number of tweets each day. At least this way we can extend it in the future if we'd like to, to be able to show number of #h5yr hashtags used since a set date.

**Comment by OwainWilliams** [comment]
That would be amazing @KarlButler1

**Comment by TECKSPEED** [comment]
@KarlButler1 interested as well let me know if you want to potentially work together on this.

**Comment by KarlButler1** [comment]
Hi @TECKSPEED, Sorry I jumped ahead on this one and only had a few small bits to finish on this, this evening before it was all done.

Happy to talk you through what I've done in this PR, if that'll be of benefit to you. I'll be doing a blog post on this within the next couple of weeks too so hopefully this'll be useful too.

**Comment by TECKSPEED** [comment]
@KarlButler1 hey no problem, no harm no foul. Glad it got done!

**Comment by TECKSPEED** [comment]
@KarlButler1 i think the only part I would really be curious about is how you worked with NPoco or whatever ORM to get the data out and into the DB as I'm used to stored procedures!

**Comment by OwainWilliams** [comment]
oh oh! @KarlButler1 - Just deployed this to LIVE and the count doesn't look to be working. Unless it's a scheduled thing that I've missed. If I get a chance, I'll look in to the issue, otherwise, if you could look too, that would be great.

**Comment by KarlButler1** [comment]
Hi @OwainWilliams, it runs on a scheduled tasks every 6 hours, which will grab the number of tweets for the day. I'll have a check later on to make sure it's working as it should.
