### ISSUE TITLE
Improve initial Readme file.

### ISSUE THREAD

**Issue by OwainWilliams** [H5YR/High5YouRock#17]
The initial readme could probably be fleshed out a bit more to help others get started with the project.

**Comment by OwainWilliams** [comment]
The readme file needs to be updated to reflect that we aren't using Twitter any more

**Comment by manancodes** [comment]
What information do you want to add? I would like to work on this. 

Also loved your H5YR sticker on holopin, how can I get that?

**Comment by OwainWilliams** [comment]
Hi @manancodes - the H5YR badge can be claimed for free via - https://holopin.io/collect/clfcrtna163140fjsf31nv3ww :) 

The readme needs updated to help people get started with the site. Removing the twitter information and adding new info for the mastodon service that is now on the site.

**Comment by manancodes** [comment]
Thanks for the badge.

For updating the Readme, I have to understand the working of the website. I will try to work on this. But anybody who understand the working of mastodon, feel free to take this one over.
