### ISSUE TITLE
Allow Hacktoberfest contributions

### ISSUE THREAD

**Issue by glombek** [H5YR/High5YouRock#30]
It'd be great if H5YR was eligable for both Hacktoberfest and Umbraco's Hacktoberfest!

Umbraco has a guide for how to do both: https://github.com/umbraco/Umbraco.Packages/tree/main/Hacktoberfest2023#package-maintainers

**Comment by OwainWilliams** [comment]
Thanks @glombe I'll get the project added tomorrow. 👍

**Comment by OwainWilliams** [comment]
Added, awaiting PR approval :)
