### ISSUE TITLE
Update Libsass due to Python Dependency

### ISSUE THREAD

**Issue by OwainWilliams** [H5YR/High5YouRock#35]
Thanks to Warren for flagging that Libsass has a dependency on Python and that it would be a good idea to update the FE build for this project. 

https://sass-lang.com/blog/libsass-is-deprecated/

Can anyone help with this?

**Comment by glombek** [comment]
It might be worth replacing the whole gulp pipeline with something more up-to-date (but not just "trendy"!) like Webpack (seem's to be weathering the storm) or Vite (may not be fully suited to this) or Bun (might just be trendy).

**Comment by OwainWilliams** [comment]
Also - however this is replaced, the Readme file should be updated with instructions on what is needed.

**Comment by JasonElkin** [comment]
I've made a start. 

As @glombek points out, the best way to handle this problem is with a more modern build process. Gulp 3 doesn't work on modern node either and managing old node dependencies is a pain. A wholesale replacement with Vite should be pretty straightforward.
