### ISSUE TITLE
Create a way to not require API keys to test the site

### ISSUE THREAD

**Issue by OwainWilliams** [H5YR/High5YouRock#4]
What I'm thinking here is maybe to have a flag in a config that says "TestMode = true" and when this is set, instead of using the twitter api, we return fake tweets, say 20 of them, in a list. This would mean people don't need API keys just to get the site to run.

**Comment by OwainWilliams** [comment]
I've got a list of test tweets working - I just need to set up some logic to accept a testmode parameter.

**Comment by prjseal** [comment]
Why not just check if it has an api key set then use live mode and if not use test mode?

**Comment by markadrake** [comment]
I signed up for access to the Twitter API, which is not an automated process. 

I would like to ditto Paul's comment above – if no secrets are found, or if the secrets fail, the site could gracefully fall back into demo mode. I would recommend that demo mode show some sample tweets and include a message about why the site is in demo mode.

I've identified at least two scenarios where tweets may not load. 

1 - There are no secrets at all. The application currently tries to make a request anyways. We should catch this.
2 - The request fails for auth reasons. We could catch this too.

This is just a quick illustration of the warning to the user.

https://user-images.githubusercontent.com/713355/177920886-1889d146-1d83-4b03-ad32-7c5bd1463e32.mp4

**Comment by OwainWilliams** [comment]
What I've done is created a AppSetting for OfflineMode - the reason for this is I have an API key setup but I wanted to be able to test the site without always using my API key. 
This has now been setup and is deployed. 

All I do is spoof some tweets from a Json file. This means we still "see" what the site should look like and if any front end changes are needed to do with the tweets it can still be done.
