### ISSUE TITLE
Tidy up Twitter code in project

### ISSUE THREAD

**Issue by CodeBunTes** [H5YR/High5YouRock#50]
With it looking unlikely we will see a return to being able to use Twitter/X's Free API now, would it make sense to possibly look at cleaning up and removing a lot of the old Twitter code still remaining in the project? With only the active Mastodon code left in, it should be easier to follow for any new people, and would also mean things like the intermittent exception that pops up from the old Twitter code when running the project in debug mode locally would go away.

Happy to take this one on and submit a PR for it, but thought I'd throw it up here as a discussion first anyway incase anyone has any views.

**Comment by OwainWilliams** [comment]
yup, removing twitter is probably a good move. I can't see it coming back any time soon or a free tier.
